#!/usr/bin/python

#import numpy as np
#import matplotlib.pyplot as plt
import pylab as plt
import os
from numpy import *
wrkDir = os.getcwd()
import matplotlib as mpl
mpl.rcParams['lines.linewidth'] = 2
mpl.rcParams['font.size'] = 18
#print "current working directory: " + str(wrkDir)
#pipeStartDir = wrkDir + "/phi_pipeStart"

#print "current working directory: " + str(pipeStartDir)
def parseFaceSource(parseDir,parseOutName):
	parseFiles = []
	for (dirpath, dirnames, filenames) in os.walk(parseDir):
#		print "current dirpath = " + str(dirpath)
		for filename in filenames:
			if filename == "faceSource.dat":
				parseFiles.append(dirpath + str("/faceSource.dat"))

#print pipeStartFiles
	parseOut = parseDir + "/" + parseOutName
#	print pipeStartPath
	try: 
		os.remove(parseOut)
	except OSError:
		print "Following file couldn't be removed: ",parseOut
	for filepath in parseFiles:		
		with open(parseOut,"a") as out:
			for line in open(filepath):
				if line[0] != "#":
					line = line.replace(")","").replace("(","").replace('\t',' ')
					out.write(line)

pipeStartPath = wrkDir + "/phi_pipeStart"
pipeEndPath = wrkDir + "/phi_pipeEnd"
throatPath = wrkDir + "/phi_throat"
nozzleEndPath = wrkDir + "/phi_nozzleEnd"

parseFaceSource(pipeStartPath,"phi.dat")
parseFaceSource(pipeEndPath,"phi.dat")
parseFaceSource(throatPath,"phi.dat")
parseFaceSource(nozzleEndPath, "phi.dat")
fig = plt.figure()

data = plt.loadtxt(pipeStartPath + "/phi.dat")
phi = [sqrt(data[i,2]*data[i,2] + data[i,3]*data[i,3]) for i in range(0,len(data[:,2]))]
pipeStartPlot = plt.plot( 1000*data[:,0], 180*1000*data[:,2], 'ro', label="Inlet channel start" )
#plt.setp(pipeStartPlot,color='ro')

data = plt.loadtxt(pipeEndPath + "/phi.dat")
pipeEndPlot = plt.plot( 1000*data[:,0], 180*1000*data[:,2], 'go', label="Inlet channel end" )
#plt.setp(pipeEndPlot,color='go')

data = plt.loadtxt(throatPath + "/phi.dat")
throatPlot = plt.plot( 1000*data[:,0], 180*1000*data[:,2], 'bo', label="Nozzle throat" )
#plt.setp(throatPlot,color='bo')

try:
	data = plt.loadtxt(nozzleEndPath + "/phi.dat")
	throatPlot = plt.plot( 1000*data[:,0], 180*1000*data[:,2], 'rx', label="Nozzle exit" )
except IOError:
	print "Can't find folder " + nozzleEndPath


plt.legend(prop={'size':18})
#plt.title(wrkDir)
plt.ylabel("Mass flow [g/s]")
plt.xlabel("time [ms]")
plt.grid(True)
fig.patch.set_facecolor('white')
os.chdir('/home/tptatu/Dropbox/Koulu/Dippa/Latex/images')
plt.show()



'''
for (dirpath, dirnames, filenames) in os.walk(pipeStartDir):
	print "current dirpath = " + str(dirpath)
	for filename in filenames:
		if filename == "faceSource.dat":
			pipeStartFiles.append(dirpath + str("/faceSource.dat"))

print pipeStartFiles
pipeStartPath = wrkDir + str("/pipeStartPhi.dat")
print pipeStartPath
os.remove(pipeStartPath)
for filepath in pipeStartFiles:		
	with open(pipeStartPath,"a") as out:
		for line in open(filepath):
			if line[0] != "#":
				line = line.replace(")","").replace("(","").replace('\t',' ')
				out.write(line)
'''
